### PR TITLE
Move the reusable code from handlers to api

### PR DESCRIPTION
**Pull request by std4lqi**
Signed-off-by: Qi Liang <31643673+std4lqi@users.noreply.github.com>

### CODE REVIEW

**Comment by lauren-li** [comment]
@std4lqi So far in my testing, this is looking good! Your reminder to set `JESINTERFACELEVEL` to 2 was helpful, and most of the tests are passing for me now. I still get a couple failing where the test appears to be waiting for the job to complete, but I get the same tests failing on `master` branch, and it is perhaps an issue with our server.

One important thing that seems to be missing from this PR are the `index.ts` files in the `src/api` folder to export everything. Those will be needed so that classes and methods inside the folder can be accessed when Zowe Explorer makes calls such as list or download. Each folder level within `src/api` will need an `index.ts` file to `export *` from all of its files and subfolders that we want to make available through the API. Additionally, in the top level `src/index.ts`, we want to add the line: `export * from './api’;`.

We would want to add the following `index.ts` files:
- `src/api/index.ts`
  - An example snippet of what would be in `src/api/index.ts`:
    ```
        export * from "./docs";
        export * from './AbstractTemplatedJCL';
        export * from './CoreUtils';
    ```
- `src/api/doc/index.ts`

(Thanks to my teammate @JillieBeanSim for pointing this out to me!)

**Comment by std4lqi** [comment]
@lauren-li Thanks for comments! I added `api/index.ts`. 

For the system test, you may run `npm run test:system -- --runInBand` one by one to avoid interfering with each other, especially submitting job. Let me know please, if any problem with waiting for the job to complete again.

**Comment by lauren-li** [comment]
@std4lqi Thank you for adding in the `index.ts` files! Could you please also add the export API line in `src/index.ts`?:
> Additionally, in the top level `src/index.ts`, we want to add the line: `export * from './api’;`.

~
I am still having some issues with a few of the jobs tests after following your suggestion to run `npm run test:system -- --runInBand` one by one. The error I get for the failing tests all look similar to this:
Screen Shot 2020-12-09 at 11 32 50 AM

When I run the suggested command (e.g. `zowe zos-ftp view job-status-by-jobid JOB06625` in this case), the result looks like the job completed successfully:
Screen Shot 2020-12-09 at 11 38 55 AM

**Comment by std4lqi** [comment]
@lauren-li , I'm afraid `SLEEP.JCL` sleeping for 20 seconds might be sensitive to time. Could you change `3,5` to a longer one like `3,10`, and try it again?

**Comment by lauren-li** [comment]
Thanks @std4lqi for the suggestion! It seems `3, 10` is still a bit too short in my testing, but I was able to get more of these tests passing with `5, 10`, and all of them passing with `6, 10`. Is there a similar adjustment I could make in the tests for `should be able to submit a job from a local file with wait-for-active option and get rc successfully`? These tests are failing for me with the following output:
Screen Shot 2020-12-11 at 3 49 28 AM

When I run `zowe zos-ftp view job-status-by-jobid JOB06882` after the tests complete, I get the following status:
Screen Shot 2020-12-11 at 3 49 52 AM

~
Also (apologies for the repetition), it seems this PR is still missing the line `export * from './api’;` in the top level `src/index.ts` file.

**Comment by std4lqi** [comment]
Hi @lauren-li , `src/index.ts` is updated now.

I don't understand well why `status` is `INPUT` shows up with `Job is active`.  

Hmm. This is my output. Can you run this case only, by changing `it` to `it.only`? Or is the option `--wait-for-active` able to work from CLI?
```
Submitted job successfully, jobname(jobid): SLEEP(JOB10324)
    Waiting for job completion.
    Job is active.
    jobid:   JOB10324
    jobname: SLEEP
    owner:   IBMUSER
    status:  ACTIVE
```

**Comment by std4lqi** [comment]
@lauren-li After looking at the code carefully again, I found `jobDetails` was used wrong in the case of --wait-for-active. The `jobDetails1` is renamed to `currentJobDetails` now to avoid potential mistake in future. Thanks!

**Comment by lauren-li** [comment]
Thanks @std4lqi for looking into the `--wait-for-active` issue! With your latest change, all unit and system tests now pass for me on this PR branch. (I do still have to change `wait` from `3,5` to a larger value like `6,10` in the tests as you recommended to me earlier, though.) I am also able to successfully execute the `submit…` commands with the `wait-for-active` option manually in the CLI.

~
In manually testing a build from this PR branch with the Zowe Explorer FTP Extension, I saw one potential point of regression: When I try to open a USS file in the Zowe Explorer USS view, I now get the following error:
Screen Shot 2020-12-15 at 3 13 23 AM

This may have to do with changes made to the `StreamUtils` class, particularly the `streamToStream` function (which is used in `USSUtils`' `downloadFile` method). However, I do not get any errors when using zftp's `download uss` command in the CLI. When using using a build generated from zowe-cli-ftp-plugin's `master` branch, I do not encounter this issue with the Zowe Explorer FTP Extension.

Other USS functionalities that I tested with the Zowe Explorer FTP Extension appear to be working well!

**Comment by std4lqi** [comment]
@lauren-li I updated `__tests__/__system__/cli/submit/local-file/cli.submit.local-file.test.ts` to wait for 30 seconds to ensure the job finishes before timeout. 

For Zowe Explorer FTP Extension, you may need Tina's PR https://github.com/zowe/zowe-explorer-ftp-extension/pull/11/, which was updated to use the new API, including the changes for `StreamUtils`.

**Comment by lauren-li** [comment]
@std4lqi You are right! I tried pasting in all changes of Tina's PR into my local Zowe Explorer FTP Extension repository, and opening a USS file with a FTP profile in Zowe Explorer works great with it.

@tiantn, perhaps you could go ahead and transfer the contents of your PR zowe/zowe-explorer-ftp-extension#11 into a PR against the [ZoweExplorerFtpApi file](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpApi.ts) of Zowe Explorer's zowe-explorer-ftp-extension package, and we could work with @zFernand0 to coordinate the release between these two PRs?

**Comment by std4lqi** [comment]
@zFernand0 Shall we upgrade zftp version to 1.3.0, indicating API package is available?

**Comment by zFernand0** [comment]
> @zFernand0 Shall we upgrade zftp version to 1.3.0, indicating API package is available? 

I guess my only concern is the `findJobByID` api that changed its parameter order (e.g. `jobID, connection` to `connection, jobID`)

However, since the APIs were not explicitly exposed before (meaning , someone had to import from `"@zowe/plugin/lib/api/JobUtils`), we could get away with not publishing a breaking change (v2.0.0)

Going forward (and including the Zowe-Explorer-PR#1111), all apps can just import the APIs from the package (without `lib/api`)

**Review by zFernand0 — APPROVED** [review]
Works like a charm.
Love to be able to use the APIs properly now!
LGTM!
Will wait on others inout on whether the version should be 1.3.0 or 2.0.0

**Comment by lauren-li** [comment]
@std4lqi  I think this PR looks good now! All tests are passing for me (although, I _still_ have to increase the time for the `submit job with wait option` ones). The Zowe FTP CLI plugin functionality seems to still be working well in my manual testing, and the newly-exposed APIs also pair nicely with [Tina’s PR 1111](https://github.com/zowe/vscode-extension-for-zowe/pull/1111). I would approve this PR, but I don't think I actually have permissions to do that.

Regarding version number, I trust Fernando’s decision. If we decide to go with 1.3.0 but have concerns about the new order of `findJobByID` parameters (which I think is a good change), perhaps we could update the changelog to specifically mention the parameter order switch.

**Comment by zFernand0** [comment]
Thanks@lauren-li  and thanks @std4lqi 
Let's go with 1.3.0 and have a proper changelog "warning" about the change in the parameter order.
Once the ZE PR gets merged, we can proceed to publish this enhancements (before 1.11.1 goes out)

**Review by lauren-li — APPROVED** [review]
I just realized I am able to add my formal approval on this PR, so here it is! :)

Thanks @std4lqi for your hard work on this PR!

**Pull request merged**
